import Head from 'next/head';
import { SearchIcon, MicrophoneIcon } from '@heroicons/react/solid';
import { useRouter } from 'next/router';
import { useRef } from 'react';

import Header from '../components/Header';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const handleInputSearch = event => {
    event.preventDefault();

    const term = searchInputRef.current.value.trim();

    if (!term) {
      return;
    } else {
      router.push(`/search?term=${term}&searchType=`);
    }
  };

  const handleRandomSearch = async event => {
    event.preventDefault();

    const randomTerm = await fetch(
      'https://random-word-api.herokuapp.com/word?number=1'
    ).then(res => res.json());

    if (!randomTerm) {
      return;
    } else {
      router.push(`/search?term=${randomTerm}&searchType=`);
    }
  };

  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <form className="flex flex-col items-center mt-40">
          <img
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/640px-Google_2015_logo.svg.png"
            alt="Google Logo"
            className="w-72 object-cover"
          />
          <div className="flex w-full mt-5 mx-auto max-w-[90%] border border-gary-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl">
            <SearchIcon className="h-5 text-gray-500 mr-3" />
            <input
              ref={searchInputRef}
              type="text"
              className="flex-grow focus:outline-none"
            />
            <MicrophoneIcon className="h-5 text-gray-500 mr-3" />
          </div>
          <div className="flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
            <button onClick={handleInputSearch} className="btn">
              Input Search
            </button>
            <button onClick={handleRandomSearch} className="btn">
              Random Search
            </button>
          </div>
        </form>
      </main>

      <footer className="absolute bottom-5 w-[100%] text-center text-gray-700 text-sm">
        <p>Copyright &copy; {new Date().getFullYear()}</p>
      </footer>
    </div>
  );
}
